/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/aventador.glb
Author: BlackCube (https://sketchfab.com/blackcube4)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lamborghini-aventador-2263b49846d840618046538012720c59
Title: Lamborghini Aventador
*/

import React, { useEffect, useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import { gsap } from 'gsap';
import { FLOORS, HEIGHT } from './utils/constants';

export function Aventador(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + '/models/aventador.glb')
  const ref = useRef();
  const t1 = useRef();
  const scroll = useScroll();
  useFrame(()=>{
    t1.current.seek(scroll.offset*t1.current.duration());
  })
  useEffect(() => {
    if (ref?.current) {
      ref.current.position.x = -4;
      ref.current.position.y = 1;
      ref.current.rotation.y = 0.7;
    }
  }, [ref]);
  useLayoutEffect(()=>{
    t1.current = gsap.timeline();
    t1.current.to(
      ref.current.position,{
        duration : 2,
        y:-HEIGHT *(FLOORS -1),
      },
      0
    );
  },[])
  return (
    <group {...props} dispose={null}ref={ref}>
      <group position={[0.002, 0.098, -0.012]} scale={0.001}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Carbon} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Dark_Metal} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Red_Lights} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Orange_Lights} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Aluminum} />
      </group>
      <group scale={0.001}>
        <mesh geometry={nodes.Object_13.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Carbon} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Aluminum} />
      </group>
      <group position={[0, 1.098, -0.616]} scale={0.001}>
        <mesh geometry={nodes.Object_17.geometry} material={materials.Carbon} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Dark_Metal} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Undercarriage} />
      </group>
      <group scale={0.001}>
        <mesh geometry={nodes.Object_35.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.Carbon} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.Carbon} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.Dark_Metal} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Window_Glass} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.Glass_Lights} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Undercarriage} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.Aluminum} />
      </group>
      <group position={[0, 0.103, -0.006]} scale={0.001}>
        <mesh geometry={nodes.Object_49.geometry} material={materials.Carbon} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.Front_Light_Lens} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.Glass_Lights} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.Front_Light} />
      </group>
      <group position={[0, -0.043, 0]} scale={1.494}>
        <mesh geometry={nodes.Object_59.geometry} material={materials.Carbon} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.Hubcap} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.Wheel_Screw} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.Wheel_Screw} />
      </group>
      <group position={[0, -0.043, 0]} scale={1.494}>
        <mesh geometry={nodes.Object_64.geometry} material={materials.Tires} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.Tires} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.Tires} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.Tires} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.Tires_2} />
      </group>
      <group position={[0, -0.043, 0]} scale={1.494}>
        <mesh geometry={nodes.Object_70.geometry} material={materials.Carbon} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.Brake_2} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.Brake_wire} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.Body} />
      </group>
      <mesh geometry={nodes.Object_11.geometry} material={materials.Glass_Lights} position={[0.002, 0.098, -0.012]} scale={0.001} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.Carbon} position={[0, 0.755, 1.324]} scale={0.001} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.Undercarriage} position={[0, 0.103, -0.007]} scale={0.001} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.Dark_Metal} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.Carbon} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.Exhaust} position={[0, 0.914, 0]} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.Carbon} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.Gold} scale={0.001} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.Emblem} position={[0, -0.003, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.Mirror} scale={0.001} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.Glass_Lights} position={[0, 0.103, -0.006]} scale={0.001} />
      <mesh geometry={nodes.Object_57.geometry} material={materials.Carbon} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_75.geometry} material={materials.Brake_disk} position={[0, -0.043, 0]} scale={0.164} />
      <mesh geometry={nodes.Object_77.geometry} material={materials.Window_Glass} scale={0.001} />
      <mesh geometry={nodes.Object_79.geometry} material={materials.Window_Glass} scale={0.001} />
      <mesh geometry={nodes.Object_81.geometry} material={materials.Window_Glass} scale={0.001} />
      <mesh geometry={nodes.Object_83.geometry} material={materials.Window_Glass} position={[0, 1.098, -0.616]} scale={0.001} />
    </group>
  )
}

useGLTF.preload(process.env.PUBLIC_URL + '/models/aventador.glb')
