/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/huracan.glb
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/huracan-black-panthertm-f61f211f21c442e68fb4a1fc0cc0d6ea
Title: Huracan Black-Panther™️
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { gsap } from 'gsap';
import { useFrame } from '@react-three/fiber';
export const HEIGHT = 2.3;
export const FLOORS = 3; 
export function Huracan(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + '/models/huracan.glb');
  const ref = useRef();
  const t1 = useRef();
  const scroll = useScroll();
  // useFrame(()=>{
  //   t1.current.seek(scroll.offset*t1.current.duration());
  // })
  // useLayoutEffect(()=>{
  //   t1.current = gsap.timeline();
  //   t1.current.to(
  //     ref.current.position,{
  //       duration : 2,
  //       y:-HEIGHT *(FLOORS -1),
  //     },
  //     0
  //   );
  // },[])
  return (
    <group {...props} dispose={null} ref={ref} scale={1}>
      <group rotation={[0, Math.PI / 2, 0]} scale={23.106}>
        <mesh geometry={nodes['Roues_arri��re_RIMS_BLACK_0'].geometry} material={materials.RIMS_BLACK} />
        <mesh geometry={nodes['Roues_arri��re_RIMS_BLACK_0_1'].geometry} material={materials.RIMS_BLACK} />
        <mesh geometry={nodes['Roues_arri��re_RIMS_WHITE_0'].geometry} material={materials.RIMS_WHITE} />
        <mesh geometry={nodes['Roues_arri��re_Tire_0'].geometry} material={materials.Tire} />
        <mesh geometry={nodes['Roues_arri��re_plaquette_de_frein001_0'].geometry} material={materials['plaquette_de_frein.001']} />
        <mesh geometry={nodes['Roues_arri��re_visse001_0'].geometry} material={materials['visse.001']} />
        <mesh geometry={nodes['Roues_arri��re_Material009_0'].geometry} material={materials['Material.009']} />
      </group>
      <group position={[0, 0, 131.181]} rotation={[0, Math.PI / 2, 0]} scale={23.106}>
        <mesh geometry={nodes.Roues_avant_RIMS_BLACK_0.geometry} material={materials.RIMS_BLACK} />
        <mesh geometry={nodes.Roues_avant_RIMS_BLACK_0_1.geometry} material={materials.RIMS_BLACK} />
        <mesh geometry={nodes.Roues_avant_RIMS_WHITE_0.geometry} material={materials.RIMS_WHITE} />
        <mesh geometry={nodes.Roues_avant_Tire_0.geometry} material={materials.Tire} />
        <mesh geometry={nodes.Roues_avant_plaquette_de_frein001_0.geometry} material={materials['plaquette_de_frein.001']} />
        <mesh geometry={nodes.Roues_avant_visse001_0.geometry} material={materials['visse.001']} />
        <mesh geometry={nodes.Roues_avant_Material009_0.geometry} material={materials['Material.009']} />
      </group>
      <mesh geometry={nodes.Carosserie_Black_fond_0.geometry} material={materials.Black_fond} />
      <mesh geometry={nodes.Carosserie_Black_metal__0.geometry} material={materials.Black_metal} />
      <mesh geometry={nodes.Carosserie_Chrome_0.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Carosserie_Chrome_0_1.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Carosserie_re2_0.geometry} material={materials.material} />
      <mesh geometry={nodes.Carosserie_M_2_0.geometry} material={materials.material_4} />
      <mesh geometry={nodes.Carosserie_FrontColor_0.geometry} material={materials.FrontColor} />
      <mesh geometry={nodes.Carosserie_Carrosserie_0.geometry} material={materials.Carrosserie} />
      <mesh geometry={nodes.Carosserie_Carrosserie_0_1.geometry} material={materials.Carrosserie} />
      <mesh geometry={nodes.Carosserie_window_0.geometry} material={materials.window} />
      <mesh geometry={nodes.Carosserie_Vitres_0.geometry} material={materials.Vitres} />
      <mesh geometry={nodes.Carosserie_Color_B04_0.geometry} material={materials.Color_B04} />
      <mesh geometry={nodes.Carosserie_f_light3_0.geometry} material={materials.f_light3} />
      <mesh geometry={nodes.Carosserie_f_light1_0.geometry} material={materials.f_light1} />
      <mesh geometry={nodes.Carosserie_f_light2_0.geometry} material={materials.f_light2} />
      <mesh geometry={nodes.Carosserie_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.Carosserie_black5_0.geometry} material={materials.black5} />
      <mesh geometry={nodes.Carosserie_Miroir_0.geometry} material={materials.Miroir} />
      <mesh geometry={nodes.Carosserie_r_light0_0.geometry} material={materials.r_light0} />
      <mesh geometry={nodes.Carosserie_r_light3_0.geometry} material={materials.r_light3} />
      <mesh geometry={nodes.Carosserie_r_light2_0.geometry} material={materials.r_light2} />
      <mesh geometry={nodes.Carosserie_r_light4_0.geometry} material={materials.r_light4} />
      <mesh geometry={nodes.Carosserie_CHrom_0.geometry} material={materials.CHrom} />
      <mesh geometry={nodes.Carosserie__Color_B04_2_0.geometry} material={materials.Color_B04_2} />
      <mesh geometry={nodes.Carosserie_Cabonne_0.geometry} material={materials.Cabonne} />
      <mesh geometry={nodes.Carosserie_Head_0.geometry} material={materials.Head} />
      <mesh geometry={nodes.Capot_window_0.geometry} material={materials.window} />
      <mesh geometry={nodes.Capot_Cabonne_0.geometry} material={materials.Cabonne} />
      <mesh geometry={nodes.Carosserie002_Vitres_0.geometry} material={materials.Vitres} />
      <mesh geometry={nodes.Carosserie002_Material013_0.geometry} material={materials['Material.013']} />
      <mesh geometry={nodes.Toit_Toit_0.geometry} material={materials.Toit} />
      <mesh geometry={nodes.Elargissement_Cabonne_0.geometry} material={materials.Cabonne} />
      <mesh geometry={nodes.Elargissement_Carrosserie_0.geometry} material={materials.Carrosserie} />
    </group>
  )
}

useGLTF.preload(process.env.PUBLIC_URL + '/models/huracan.glb')
