/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/urus_absoluttm.glb
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/urus-absoluttm-914bbca2f7f54783a00062a695bae0ea
Title: Urus Absolut™️
*/

import React, { useEffect, useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { gsap } from 'gsap';
import { useFrame } from '@react-three/fiber';
export const HEIGHT = 2.3;
export const FLOORS = 3; 
export function Urus(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + '/models/urus_absoluttm.glb');
  const ref = useRef();
  const t1 = useRef();
  const scroll = useScroll();
  useFrame(()=>{
    t1.current.seek(scroll.offset*t1.current.duration());
  })
  useLayoutEffect(()=>{
    t1.current = gsap.timeline();
    t1.current.to(
      ref.current.position,{
        duration : 2,
        y:-HEIGHT *(FLOORS -1),
      },
      0
    );
  },[])

  useEffect(() => {
    if (ref?.current) {
      ref.current.position.x = 2;
      ref.current.position.y = 0;
      ref.current.rotation.y = -0.5;
      console.log(ref.current)
    }
  }, [ref]);

  return (
    <group {...props} dispose={null} ref={ref} >
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[150.429, 176.223, 176.223]}>
          <mesh geometry={nodes['<Wheel002_Material_0'].geometry} material={materials.Material} />
          <mesh geometry={nodes['<Wheel002_Material_0_1'].geometry} material={materials.Material} />
          <mesh geometry={nodes['<Wheel002_Material_0_2'].geometry} material={materials.Material} />
          <mesh geometry={nodes['<Wheel002_Material054_0'].geometry} material={materials['Material.054']} />
          <mesh geometry={nodes['<Wheel002_Material053_0'].geometry} material={materials['Material.053']} />
          <mesh geometry={nodes['<Wheel002_CRBN_JANTE005_0'].geometry} material={materials['CRBN_JANTE.005']} />
          <mesh geometry={nodes['<Wheel002_SDC002_0'].geometry} material={materials['SDC.002']} />
          <mesh geometry={nodes['<Wheel002_SDC003_0'].geometry} material={materials['SDC.003']} />
          <mesh geometry={nodes['<Wheel002_Material072_0'].geometry} material={materials['Material.072']} />
          <mesh geometry={nodes['<Wheel002_Material072_0_1'].geometry} material={materials['Material.072']} />
          <mesh geometry={nodes['<Wheel002_Material072_0_2'].geometry} material={materials['Material.072']} />
          <mesh geometry={nodes['<Wheel002_Material071_0'].geometry} material={materials['Material.071']} />
          <mesh geometry={nodes['<Wheel002_plaquette_de_frein015_0'].geometry} material={materials['plaquette_de_frein.015']} />
          <mesh geometry={nodes['<Wheel002_visse015_0'].geometry} material={materials['visse.015']} />
        </group>
        <group position={[0, -1.713, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[130.931, 176.223, 176.223]}>
          <mesh geometry={nodes['<Wheel001_Material_0'].geometry} material={materials.Material} />
          <mesh geometry={nodes['<Wheel001_Material_0_1'].geometry} material={materials.Material} />
          <mesh geometry={nodes['<Wheel001_Material054_0'].geometry} material={materials['Material.054']} />
          <mesh geometry={nodes['<Wheel001_Material053_0'].geometry} material={materials['Material.053']} />
          <mesh geometry={nodes['<Wheel001_CRBN_JANTE005_0'].geometry} material={materials['CRBN_JANTE.005']} />
          <mesh geometry={nodes['<Wheel001_Material072_0'].geometry} material={materials['Material.072']} />
          <mesh geometry={nodes['<Wheel001_Material072_0_1'].geometry} material={materials['Material.072']} />
          <mesh geometry={nodes['<Wheel001_Material072_0_2'].geometry} material={materials['Material.072']} />
          <mesh geometry={nodes['<Wheel001_Material071_0'].geometry} material={materials['Material.071']} />
          <mesh geometry={nodes['<Wheel001_plaquette_de_frein015_0'].geometry} material={materials['plaquette_de_frein.015']} />
          <mesh geometry={nodes['<Wheel001_visse015_0'].geometry} material={materials['visse.015']} />
          <mesh geometry={nodes['<Wheel001_SDC002_0'].geometry} material={materials['SDC.002']} />
          <mesh geometry={nodes['<Wheel001_SDC003_0'].geometry} material={materials['SDC.003']} />
          <mesh geometry={nodes['<Wheel001_CRBN_JANTE009_0'].geometry} material={materials['CRBN_JANTE.009']} />
          <mesh geometry={nodes['<Wheel001_Material082_0'].geometry} material={materials['Material.082']} />
          <mesh geometry={nodes['<Wheel001_Material081_0'].geometry} material={materials['Material.081']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube003_CRB_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cube003_Material_0.geometry} material={materials.Material} />
        </group>
        <group position={[-106.494, -62.928, 8.337]} rotation={[-1.629, 0, 0]} scale={[4.639, 3.901, 3.901]}>
          <mesh geometry={nodes.Circle_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Circle_Material003_0_1.geometry} material={materials['Material.003']} />
        </group>
        <group position={[0, 0, -119]}>
          <group position={[0, -44.015, 65.812]} rotation={[Math.PI, 0, -Math.PI]} scale={0.55}>
            <group position={[0.177, 97.714, -156.929]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746}>
              <mesh geometry={nodes.yellow_Material_0.geometry} material={materials.Material} />
              <mesh geometry={nodes.yellow_CRB_0.geometry} material={materials.material} />
            </group>
            <group position={[0, 11.968, 292.626]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746}>
              <mesh geometry={nodes.silver_CRB_0.geometry} material={materials.material} />
              <mesh geometry={nodes.silver_Black_metal_0.geometry} material={materials.Black_metal} />
              <mesh geometry={nodes.silver_Material_0.geometry} material={materials.Material} />
            </group>
            <group position={[0, 129.059, 29.085]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746}>
              <mesh geometry={nodes.matt_black_Fond_0.geometry} material={materials.Fond} />
              <mesh geometry={nodes.matt_black_CRB_0.geometry} material={materials.material} />
            </group>
            <group position={[0.124, 152.897, -194.053]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746}>
              <mesh geometry={nodes.gloss_black_008_Black_metal_0.geometry} material={materials.Black_metal} />
              <mesh geometry={nodes.gloss_black_008_CRB_0.geometry} material={materials.material} />
              <mesh geometry={nodes.gloss_black_008_Material005_0.geometry} material={materials['Material.005']} />
            </group>
            <group position={[0, 109.505, -313.377]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746}>
              <mesh geometry={nodes.gloss_black_003_CRB_0.geometry} material={materials.material} />
              <mesh geometry={nodes.gloss_black_003_Black_metal_0.geometry} material={materials.Black_metal} />
              <mesh geometry={nodes.gloss_black_003_Material_0.geometry} material={materials.Material} />
            </group>
            <group position={[0.177, 97.714, -156.929]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746}>
              <mesh geometry={nodes.yellow002_Black_metal_0.geometry} material={materials.Black_metal} />
              <mesh geometry={nodes.yellow002_Material_0.geometry} material={materials.Material} />
              <mesh geometry={nodes.yellow002_CRB_0.geometry} material={materials.material} />
            </group>
            <mesh geometry={nodes.silver_003_BreaksRedPaint_0.geometry} material={materials.BreaksRedPaint} position={[0, 38.861, 280.29]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.silver_002_CRB_0.geometry} material={materials.material} position={[0, 10.161, -116.09]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.matt_black_001_GreyElements_0.geometry} material={materials.GreyElements} position={[0.082, 36.83, 314.587]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_050_BlackPaint_0.geometry} material={materials.BlackPaint} position={[97.377, 136.812, 284.925]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_049_BreakDiscs_1_0.geometry} material={materials.BreakDiscs_1} position={[0, 134.122, 287.404]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_046_BreakDiscs_1_0.geometry} material={materials.BreakDiscs_1} position={[0, 125.878, 254.503]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_045_BlackPaint_0.geometry} material={materials.BlackPaint} position={[134.452, 125.025, 267.18]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_044_BlackPaint_0.geometry} material={materials.BlackPaint} position={[144.589, 127.241, 255.248]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_043_BreakDiscs_1_0.geometry} material={materials.BreakDiscs_1} position={[0, 133.365, 271.34]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_042_BreakDiscs_1_0.geometry} material={materials.BreakDiscs_1} position={[0, 121.018, 262.467]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_040_Material006_0.geometry} material={materials['Material.006']} position={[0, 93.18, -497.126]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_033_Default_Material_0.geometry} material={materials.Default_Material} position={[141.975, 96.694, -474.547]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_027_Material004_0.geometry} material={materials['Material.004']} position={[0, 92.783, -496.746]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_024_BlackPaint_0.geometry} material={materials.BlackPaint} position={[-97.377, 136.812, 284.925]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_022_BreakDiscs_0.geometry} material={materials.BreakDiscs} position={[0, 126.693, 241.403]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_021_Light_RED_0.geometry} material={materials.Light_RED} position={[0, 128.601, 274.474]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_019_BlackPaint_0.geometry} material={materials.BlackPaint} position={[-134.452, 125.025, 267.18]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_018_BlackPaint_0.geometry} material={materials.BlackPaint} position={[-144.589, 127.241, 255.248]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_015_Hub_0.geometry} material={materials.material_13} position={[0, 95.296, -469.605]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_009_Light__0.geometry} material={materials.Light} position={[0, 90.942, -495.029]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_008_Material004_0.geometry} material={materials['Material.004']} position={[0, 86.076, -497.19]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_007_Default_Material_0.geometry} material={materials.Default_Material} position={[-141.975, 96.694, -474.547]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_002_BreakDiscs_0.geometry} material={materials.BreakDiscs} position={[0, 92.4, -499.12]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.lights_Hub_0.geometry} material={materials.material_13} position={[0, 150.589, -214.787]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.gloss_black_007_CRB_0.geometry} material={materials.material} position={[0, 179.623, -67.835]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.gloss_black_005_CRB_0.geometry} material={materials.material} position={[0, 30.247, 277.475]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.gloss_black_004_CRB_0.geometry} material={materials.material} position={[0, -6.843, -145.25]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.gloss_black_002_CRB_0.geometry} material={materials.material} position={[0, 64.206, -137.569]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.gloss_black_001_CRB_0.geometry} material={materials.material} position={[0, 130.707, 297.042]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.gloss_black_Black_metal_0.geometry} material={materials.Black_metal} position={[0, 6.461, -516.938]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.glass_005_Material008_0.geometry} material={materials['Material.008']} position={[0, 38.841, 281.622]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.glass_003_Vitres_0.geometry} material={materials.Vitres} position={[-0.405, 174.329, -27.919]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.glass_002_Material_0.geometry} material={materials.Material} position={[0, 150.588, -214.804]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.yellow001_CRB_0.geometry} material={materials.material} position={[0.177, 97.714, -156.929]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.yellow003_CRB_0.geometry} material={materials.material} position={[0.177, 97.714, -156.929]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
            <mesh geometry={nodes.yellow004_CRB_0.geometry} material={materials.material} position={[0.177, 97.714, -156.929]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
          </group>
        </group>
        <mesh geometry={nodes.Cube_CRB_0.geometry} material={materials.material} position={[0, 1.068, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube001_CRB_0.geometry} material={materials.material} position={[0, 51.15, -216.666]} rotation={[-1.662, 0, 0]} scale={67.558} />
        <mesh geometry={nodes.Cube002_CRB_0.geometry} material={materials.material} position={[0, 145.652, -234.049]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <group position={[0, 0, -119]}>
          <group position={[0, -44.015, 65.812]} rotation={[Math.PI, 0, -Math.PI]} scale={0.55}>
            <mesh geometry={nodes.yellow005_Material_0.geometry} material={materials.Material} position={[0.177, 97.714, -156.929]} rotation={[-Math.PI / 2, 0, 0]} scale={2.746} />
          </group>
        </group>
        <mesh geometry={nodes.Cube004_SDC_0.geometry} material={materials.material_31} position={[0, 156.79, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[1.034, 100, 8.607]} />
        <mesh geometry={nodes['<Wheel003_Material045_0'].geometry} material={materials['Material.045']} position={[0, 1.947, 253.194]} rotation={[-2.363, 0.611, Math.PI / 2]} scale={[166.273, 194.784, 194.784]} />
        <mesh geometry={nodes.wheels3002_Material_0.geometry} material={materials.Material} position={[0.942, 27.256, -217.432]} rotation={[-1.151, -0.802, Math.PI / 2]} scale={137.038} />
        <mesh geometry={nodes['<Wheel004_Material045_0'].geometry} material={materials['Material.045']} position={[73.81, 43.707, -151.55]} rotation={[-2.244, -0.744, 2.79]} scale={[269.794, 316.055, 316.055]} />
        <mesh geometry={nodes['<Wheel005_Material045_0'].geometry} material={materials['Material.045']} position={[-73.197, 43.849, -151.55]} rotation={[-0.773, 0.482, -0.55]} scale={[269.794, 316.055, 316.055]} />
        <mesh geometry={nodes.Sous001_Material001_0.geometry} material={materials['Material.001']} scale={114.679} />
        <mesh geometry={nodes.Cube005_SDC_0.geometry} material={materials.material_31} position={[0, -31.064, 246.259]} rotation={[1.987, 0, 0]} scale={[1.034, 100, 8.607]} />
        <mesh geometry={nodes['<Wheel006_Material007_0'].geometry} material={materials['Material.007']} position={[165.743, -77.222, -0.715]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[1054.717, 1419.567, 1419.567]} />
        <mesh geometry={nodes.glass001_glass_0.geometry} material={materials.glass} position={[0, -87.103, 60.369]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={1.515} />
      </group>
    </group>
  )
}

useGLTF.preload(process.env.PUBLIC_URL + '/models/urus_absoluttm.glb')